version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # Port for agent connections (AMQP)
      - "15672:15672"  # Port for the Management UI
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  
  chromadb:
    image: chromadb/chroma:0.4.15
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - ~/.docker-conf/chromadb/data/:/chroma/chroma

  actor_agent:
    build: .
    container_name: actor_agent
    ports:
      - "8003:8003"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
    restart: on-failure
    env_file:
      - .env

    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000